[package]
name = "rusterm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
crossterm = "0.24"  # or the latest version
dialoguer = "0.6" # or the latest version
ping-rs = "0.1.2"
dns-lookup = "2.0.4"